parameters:
    config.path: './app/config.yml'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Component\HttpFoundation\Session\SessionInterface:
        alias:  Symfony\Component\HttpFoundation\Session\Session

    PHPCensor\Common\Application\ConfigurationInterface:
        alias:  PHPCensor\Configuration

    PHPCensor\DatabaseManager:

    PHPCensor\StoreRegistry:

    PHPCensor\Store\:
        resource: '../src/Store/*'

    PHPCensor\Controller\:
        resource: '../src/Controller/*'
